### ISSUE TITLE
Feature request : Option to not add current route to backstack when navigating

### ISSUE THREAD

**Issue by Tolriq** [KaustubhPatange/navigator#16]
Something like noHistory : Boolean.

For example for a welcome screen that should not be returned to after navigating to real content while still allowing a single root route and proper integrated animations when using that route.

**Comment by KaustubhPatange** [comment]
This is simple, all you have to do is use `popUpTo` just like the Navigation Component.

Let's take an example:

Consider the navigation route, `ScreenA -> ScreenB -> Main`. We are currently at `ScreenB`, but now we need to navigate to `Main` such that the navigation stack should look like `ScreenA -> Main`. This problem can be solved easily using `popUpTo` option.

```kotlin
controller.navigateTo(Main) {
    popUpTo(ScreenB) // default inclusive
}
```

**Comment by Tolriq** [comment]
Yes but you are coupling the screen with the route. Screens should know nothing about navigation internals (and multiple routes could display the same destination).

If we move those up it brings repetitive code like 
```
if (noHistory) {
                    val currentDestination = controller.getAllHistory().firstOrNull()
                    if (currentDestination != null) {
                        popUpTo(currentDestination)
                    }
                }
```
```
if (clearTop) {
                    val currentDestination = controller.getAllHistory().lastOrNull()
                    if (currentDestination != null) {
                        popUpTo(currentDestination)
                    }
                }
```

That sounds like things that could be native to the library

**Comment by KaustubhPatange** [comment]
> Screens should know nothing about navigation internals (and multiple routes could display the same destination).
> That sounds like things that could be native to the library

This is something that should be solved within the app & not by the library. A library is there to make your workflow easier, it gives you functionality to use but it doesn't tell you how to get it architecturally correct. This sounds more of an architecture problem (app) rather than a library.

For example, if you don't want to couple the navigation logic in the screen, build a helper class that wraps this navigation library & use that in your code so that you don't directly depend on the library but on a wrapper that encapsulates it. You can then change the navigation system in the future if you want or if you don't like you can always depend on the reactive concept (Event, Logic & Handler) to make navigation stateful.

**Comment by Tolriq** [comment]
> This sounds more of an architecture problem (app) rather than a library.

That's the whole point :) Having the Route forced to be known by the destination is an architecture problem more or less forced by the library. It's a wrong dependency direction.

Normal activity / fragment have the notion of clearTop and noHistory hence the request as it's common navigation pattern.

A fragment should not be tied to it's activity so that it can be reused. This is the same here, a destination should not be tied to a route so that it can be reused.

With multiple backstacks you could have RootRoute.X that shows the screen and SubRoute.Y that shows the same screen probably with different arguments or not.

For the current destination to navigate away without being kept in history it needs to know from what route it's displayed this is a wrong dependency direction.
Add to this dialog route and in the future bottomsheet routes and it's a lot of burden put on the client to know what to do as a screen potentially be used in all 3 different cases with 3 different history.

Anyway yes we can hack something at higher level to mimic that, but those concept of inverted dependency and navigation pattern are IMO normal and basic use  case.

**Comment by KaustubhPatange** [comment]
> a destination should not be tied to a route so that it can be reused.

I think we are missing something, from what I see a destination or more specifically a Screen should not be reused. What I mean by that is one screen should not represent multiple screens (that can be changed through arguments) because each screen is unique (of course in cases like the progress bar it is okay because it ties to the same logic coming from one state). You can show & hide some of the components based on the arguments but the complete screen. If you need something like this then you should create a reusable component that can be reused to construct multiple screens.

This doesn't mean you cannot navigate to this screen from a different navigation route so you should tie Screen with Route because now you will always know what that route always represents. Navigation component does this exact same thing through `composable` extension function which adds your binds your current route to the content of the lambda (same goes with simple stack i.e concept of ScreenKey which actually ties Screen). This is the same reason such navigation system doesn't enforce duplicate routes as this breaks the principle of navigation.

Summary: My point is simple Screen must be tied to a route for predictable navigation. You can always construct using reusable components but don't use a Reusable Screen that doesn't sound good.

The issue with fragment was even though you don't directly tie it to the activity / navigation system directly (suppose you are using Navigation Component) they actually do! The same concept goes if you have multiple feature modules where you expose the destination through a dependency injection pattern. We think we've reduced coupling but we don't since now we depend on `@Inject` able fragment at runtime.

> With multiple backstacks you could have RootRoute.X that shows the screen and SubRoute.Y that shows the same screen probably with different arguments or not.

This is an antipattern & is completely against the navigation principle. As I said you should make each destination unique. If you are showing the same screen with two different routes then you are duplicating the logic. What you should do is create a set of arguments for a single route & use that route in nested navigation (navigator-compose will take care of the rest) as your nested navigation doesn't about parent navigation.

> For the current destination to navigate away without being kept in history it needs to know from what route it's displayed this is a wrong dependency direction.

You showed the code in above comment similar to this `val currentDestination = controller.getAllHistory().lastOrNull()`. Now question is do we know what this route is from the code? We don't we just know it is something that extends `Route` class so you can easily pop it.

> Add to this dialog route and in the future bottomsheet routes and it's a lot of burden put on the client to know what to do as a screen potentially be used in all 3 different cases with 3 different history.

Dialogs can be and should be reused because they are dialogs. That's one of the things I don't like with the Navigation Component, they make you believe that a dialog is a part of navigation but it's not since it is always going to be displayed on the top of the existing Screen. That's why my way of creating dialog is to explicitly tell `Controller` to create a dialog and then `show` it.

Also, you should not stack multiple dialogs over one another thinking that you would pop it. That's not why they are there. They are dialogs and should be used as dialogs, not as Screens i.e allow users to interact with the screen by showing some options, etc.

A dialog will never be a problem as during creation you indirectly tie a `Dialog` to a `DialogRoute` which then can be helped to show the same dialog.

> Anyway yes we can hack something at higher level to mimic that, but those concept of inverted dependency and navigation pattern are IMO normal and basic use case.

You should not hack anything. If you have a big app then consider following the reactive concept of stateful navigation, it has so many benefits.

**Comment by Tolriq** [comment]
We do mix a few things effectively.

For 

> You showed the code in above comment similar to this val currentDestination = controller.getAllHistory().lastOrNull(). Now question is do we know what route is currentDestination variable represent?

Typically this is taken from your samples and onChanged callback. Since the onChanged callback is passed and called from a route we can assume that it's the current top route from the current controller so it works.

Now about the main reusable screens for example. My app can detect "servers" and add them from different places with some configuration steps between then go to a final different place or just close and return to where we where.. Those can happens from the first run wizard, from settings, and from some bottom sheets too.

Same for dialogs that can navigate to other destinations, you can have a detail dialog that can navigate to details screens and we should be able to return to the previous place we where. But that dialog can be called for example from an album list or an artist list.

I do not see reusing all those cases an anti pattern by it self, just more complex navigation than what jetpack compose navigation offers and reason I want to use something less restrictive.

**Comment by KaustubhPatange** [comment]
> I do not see reusing all those cases an anti pattern by it self

This is not reusing the screen but reusing the route which is fine & that's what we should do.

> Same for dialogs that can navigate to other destinations, you can have a detail dialog that can navigate to details screens and we should be able to return to the previous place we where. But that dialog can be called for example from an album list or an artist list.

You can achieve it, all you need to do is to find the controller using `findController` that was used to create the dialog. The call is recursive to its parent. So it will exist as long as the destination is in the backstack.

> just more complex navigation than what jetpack compose navigation offers and reason I want to use something less restrictive.

This is not a restriction but providing a correct way for navigation. If this feature is added then there are two ways of doing one thing which is not something we want, we've seen this with Fragments eg: `addToBackStack`.

Even though it could be a valid feature request but I may not add this feature as this will break the predictable navigation. Having something to replicate `doNotAddToBackStack` may not be good as `popUpTo` solves this. Still, I'll keep this issue open for me to think whether this is something needed or not.

**Comment by Tolriq** [comment]
Thanks for looking into this, the issue is the same with cleartop. Popupto requires that the caller knows the backstack to pop to the first one.

While I understand why you want to force unique routes and the benefits. This forces to define a lot of duplicate routes to achieve all the cases if we want abstraction and to pass those routes around the destinations.

**Comment by KaustubhPatange** [comment]
I'm thinking & something got into my mind. I'll finalize the API design & then we can discuss if we need this.

**Comment by Tolriq** [comment]
If that can help https://voyager.adriel.cafe/stack-api from another library I checked at some point.

I really loved the idea of fully controllable back stacks permitting all my use cases easily.

**Comment by KaustubhPatange** [comment]
Yes, I've something similar in my mind & I'll get back to you with it.

**Comment by KaustubhPatange** [comment]
I opened a pull request (#17) related to this issue. See if it meets your needs?

**Comment by Tolriq** [comment]
Got a quite busy week end will probably only be able to check all those early next. But thanks for the fast iterations.

**Comment by KaustubhPatange** [comment]
Hey, I have published a snapshot (`0.1-alpha24-457343a-SNAPSHOT`) for the latest commit in `update` branch which adds this feature request. 

I have added all the required utilities which I think are more than enough to gain more control over the backstack. See if these changes meet your needs & try to give early feedback before merging this to master.

**Comment by KaustubhPatange** [comment]
Hey @Tolriq,

No hurry, health & family always comes first! I'll test it more & will try to find more usecase as required & will possibly merge it.

Till then, take care of you & family :)

**Comment by Tolriq** [comment]
So starting to look into that reusable nested navigation in compose and I'm lost about how to do that properly currently :(

Using a scaffold and bottom navigation first level navigation is easy: 

```
composeNavigator.Setup(key = MainRoute.key, initial = MainRoute.Home(), controller = homeController) { destination ->
                        when (destination) {
....
```

Now if page 1 wants to implements nested navigation specific to that page do the same and all works.

But when you want to have reusable and cross linked navigation routes, this becomes a lot more complicated.

When in page 1 I want to start a nested navigation to a detail screen 2 I can create a new route and do nested nav with a navigator.setup ...

When in page 2 I want to start a nested navigation to a detail screen 2 (identical to the other one). I need to create a new route and another navigator.setup and so on.

When you add all the possible cases everywhere this does not seems like the proper way, so I'm probably missing something.

Since the controller and destination are all tied to a route I don't see a way to properly describe such kind of navigation

**Comment by KaustubhPatange** [comment]
> When you add all the possible cases everywhere this does not seems like the proper way, so I'm probably missing something.

It is the proper way in my opinion. I'll tell you why? Even though you've duplicated routes (let's say D) to create nested navigation identical (to let's say B). So in a way, your backstack looks something like this `[A = {1,2}  , B = {1,2,3} , C = {1,2...} , D = {1,2,3}]`. 

Now here we know B & D are identical in nested navigation. Let's say if you reuse the existing routes the backstack route is not unique. So suppose if you want to do `popUntil` using goBackUntil(...) it is not possible. The back navigation may not produce correct results since there is the same key in the backstack (although it would be many issues because `ComposeNavigator` can handle duplicate keys). The main problem will be using `popUpTo` & other utilities that are used to manipulate the backstack.

I would suggest first try using an existing key & see if everything is working fine according to you. In any term longer if something fails you can always quickly refactor the routes (since you know IntelliJ Idea has great refactoring for classes).

Also, one thing to mention is if you reuse the routes (eg B for D), using `findController<B>(B::class)` will only retrieve the first instance of B (descending order i.e D) which means you cannot get a controller for the first B route (i.e after A) because of `CompositionLocalProvider` scoping.

**Comment by KaustubhPatange** [comment]
So suppose A,B,C are the screen in bottom navigation & A contains a nested navigation of D. Now I'm currently deeply nested in B. Suppose I have a requirement to add D as nested navigation (duplicate). What I would do is find controller of bottom navigation & I'll navigate to A with an arg that if read will navigate to D immediately & thus I'll prevent duplicate nested navigation.

So in infinite possibility cases, I think this would scale but you need to do some additional configuration to correct handle backstack.

These will change according to your app case. Since I don't know any of your app code & can't suggest any optimal way. But these would things that I would do. Also, I would first suggest that you just think (in your mind) on how would you implement this if it were a case with fragments. If you found a solution I guess doing it with compose is not time-consuming?

**Comment by Tolriq** [comment]
At the root at the bottom navigation we would have something like:

```
composeNavigator.Setup(key = MainRoute.key, initial = MainRoute.Home(), controller = homeController) { destination ->
                        when (destination) {
                            is MainRoute.Home -> HomeDestination()
                            is MainRoute.Library -> LibraryDestination()
                            is MainRoute.Search -> SearchDestination(l)
                        }
                    }
``` 

In each of those screen I'd have the nested navigation with 

```
composeNavigator.Setup(key = XRoute.key, initial = XRoute.Home(), controller = homeController) { destination ->
                        when (destination) {
                            is XRoute.Home ->
                            is XRoute.Library -> 
                            is XRoute.Search ->
                        }
                    }
``` 

I can't just have a ZRoute.artist here to reuse the route on both sub screens.

I already have a sealed interface for a start route with one route leading to the bottom navigation screen. And one sealed interface for all the possible tab destination. The artist / albums / xxx part needs to be displayed at the when XRoute place.

So please show me how you'd configure the navigator and the "when":
A: tab 1 with list of artists from bottom nav
B: tab 2 with list of albums from bottom nav
C: list of albums from an artist
D: list of artists from an album

Start on screen A, press an artist, have a list of albums press an album have a list of artist
Press B tab so press an album then an artist then an album ...

Back stack is A -> C -> D -> C -> D -> C -> B -> D -> C -> D -> C

To better visualise you can imagine that both tabs A and B are active at the same time on a tablet too.

If I press back I go back in the proper order I can press B or A to go directly to each root. All that with C D order completely reusable as there's more than 2 tabs and more than just those 2 destinations.

No need for a complete real example but more than just do something when that something does not seem possible with the current API

**Comment by Tolriq** [comment]
Voyager have no problem at all to handle that. A destination is a screen.

Just start a new navigator for a nested one then push screen details. Exactly as I do with fragment.

There's 0 complexity from their doc and samples. A screen just needs to extends Screen.

I like your approach of decoupling the content from the route giving more controls and everything at that when level. But the hard link in class hierarchy between the controller key and it's possible backstack entri

**Comment by KaustubhPatange** [comment]
> But the hard link in class hierarchy between the controller key and it's possible backstack entries annihilate that power.

Can you elaborate more on this. Do you mean that some I should support duplicate nested navigation or something else which could solve this issue?

**Comment by Tolriq** [comment]
I know my English is bad I warned a few times :) And we probably also have some terminology issues here.

The "issue" is about typing and everything being <T : Route> from the key to manage the backstack root to the controllers to the content callback from Setup().

While there is one advantage of this strong typing in all the hierarchy is that you can easily use sealed classes to force exhaustive when and everything.
But on the other end since you do use that type as the key for the root and nested navigation roots you are generating a hard immutable link between the navigation scopes and the routes / screens making things very limited.


I am absolutely not sure what is the best way to fix this in your current code internal as I have not really fully looked into and all your requirement of having the key a KClass of a Route. And there's also your terminology of calling things Route.
But in your examples / usage those Routes are just collections of Screens without any order or relation between them except being from the same "Route" so the term may induce confusion and is probably also why your library is made like it is, you are not supposed to go of road.

IMO if possible the Setup key should not be tied to the T type so we can reuse "routes" more easily (or in the worst case have 1 big sealed class that define all screens).

Depending on your internals (and I thought it was more or less like that at first) I would have a T: Route to define the "Route" and your nested nav. And a S : Screen for all the possible destinations that you can push / pop with proper typing there's maybe even still ways to provide sealed interface for the Screens for some specific Setup().

But this is a large complex architecture issue not sure this is something you want to go after.
