### ISSUE TITLE
Bug: Default transitions does not work in release builds with R8

### ISSUE THREAD

**Issue by Tolriq** [KaustubhPatange/navigator#18]
Due to https://github.com/KaustubhPatange/navigator/blob/master/navigator-compose/navigator-compose/src/main/java/com/kpstv/navigation/compose/ComposeNavigator.kt#L139 the default transitions do not work in release build.

Harcoding a string key correctly fix the issue.

**Comment by KaustubhPatange** [comment]
Did you try adding

`-keep public class * extends com.kpstv.navigation.compose.NavigatorTransition`

I was certainly sure this could be an issue so I guess I have to rather update the docs about the proguard rules or add it to consumer proguard.

**Comment by KaustubhPatange** [comment]
> That rule would keep also an unused transition for no benefits

I think serving a default proguard rule would be better rather than you explicitly specifying a new string for the transition (doesn't make that sense). I think won't add much overhead since the code is a library code. If it makes sense you can also check almost entire androidx components are excluded by proguard even if they don't require that (lol).

> could tweak something with keep names

For unused transition, I think it can be only done from the client-side since the library doesn't know which transition you are using so it makes sense for you to specify them manually.

**Comment by Tolriq** [comment]
Rules are now very fine tuned even more if you do not use appcompat / material (that's the only ones keeping more because of the invocation by reflection to replace default components) + R8 is smarter than ever.

> I think won't add much overhead since the code is a library code.
Every code that a library add that is not used and is left in final APK is increased dex size, oat compile time, disk space and is bad when you multiply by dozens of library.

> For unused transition, I think it can be only done from the client-side since the library doesn't know which transition you are using so it makes sense for you to specify them manually.

No that the opposite, a library should not keep anything that is not used explicitly by the consumer when possible. That's why you need to fine tune the rules if you decide to embed them. Imagine that when using ExoPlayer for Music Player I add to embed 2Mb of dex of the video player part that I do not use. It's better to not embed too large rules that are very hard to revert than leaving the app devs properly configure them.

If you add ```-keep public class * extends com.kpstv.navigation.compose.NavigatorTransition``` then every transition is forced to be kept and app needs to know all of them to add some assumenosideeffects that's very bad and should not be, in that case add a note and let app consumers do the proper rules.

Depending on how things are used you need to use ```-keepnames``` and eventually ```-keepclassmembernames``` for the key thing.

See https://www.guardsquare.com/manual/configuration/usage

**Comment by KaustubhPatange** [comment]
> R8 is smarter than ever

Yeah, it is smarter thanks to AGP which automatically generate those proguard-optimized.txt during compile time since it has a whole project analysis & can know what APIs are not used by 

Also, there is one thing you need to know even if you are not the default transition from the client they are still registered by the library [here](https://github.com/KaustubhPatange/navigator/blob/bc5c3a8b322748bd68e34b2fe06ece91a4a1abc9/navigator-compose/navigator-compose/src/main/java/com/kpstv/navigation/compose/ComposeNavigator.kt#L173) so R8 will never remove them which means default transition will always stay in the code even though you are not using any.

Considering this I think a consumer proguard rule could be used here instead of manually overriding key.

**Comment by Tolriq** [comment]
Again IMO, a better way would be that the default one could be overridden and not embed in the final APK.

Those are small for the moment it's still best practice, and what if you add more later, and what if any library offers new complex optional ones that will be forced by side effect of that consumer proguard rule.

A very targeted keepname may be acceptable even if far from perfect but a simple keep all that expand is IMO again a NO GO.
Rules needs to be as small as possible there's many many documentation about best practice and bad library behaviors.

Fixing your rules on the client side will be a nightmare.

**Comment by KaustubhPatange** [comment]
Now I'm thinking, the reflection-based runtime approach may not be worth it instead (since R8 with full mode doesn't even respect the name from the bytecode) it would be good that the user needs to specify the key manually.

Although I cannot add functionality to remove the default transitions since it is used by the library internally for the various purposes (eg [here](https://github.com/KaustubhPatange/navigator/blob/1185c2bdda5b8c72539c5f2c6e8d3853eee8f8e8/navigator-compose/navigator-compose/src/main/java/com/kpstv/navigation/compose/ComposeNavigator.kt#L897)). I can certainly make it explicit to specify a key for custom transition.

This change does not require any proguard optimization. Also, if I have to support any additional transition then it would in a separate add-on library (also applies to this #12 pull request for adding support to animated content transition).

**Comment by KaustubhPatange** [comment]
Forgot to link the issue during the commit, but your requested change is applied & released as `0.1-alpha23` (will be soon indexed by maven for use).

**Comment by Tolriq** [comment]
Thanks.
