### ISSUE TITLE
There is a problem with the example module

### ISSUE THREAD

**Issue by xuexixuexijpg** [KaustubhPatange/navigator#22]
Hello, I used this library as a practice code. When I first saw it, I thought this library was very useful. Then I used the leakcanary memory leak detection tool to check some code of the example, here are some problems:

### **multi-modlue-sample:**
![Snipaste_2022-05-11_16-22-40](https://user-images.githubusercontent.com/57759182/167807235-e91eead7-9778-4efb-bf5a-d6d25f492d98.png)
![Snipaste_2022-05-11_16-25-51](https://user-images.githubusercontent.com/57759182/167807276-4dc400f7-b0cd-4a5d-b345-8cdaa356c764.png)

### **navigation-sample**
![Snipaste_2022-05-11_16-40-12](https://user-images.githubusercontent.com/57759182/167807749-140d2f0d-d647-4409-9c2f-cab5e1f82f36.png)
![Snipaste_2022-05-11_16-42-12](https://user-images.githubusercontent.com/57759182/167807848-f3d89915-9a6e-4547-b659-09f118f28647.png)

Posted where the memory leaked and the modified code.The test is not complete, there may be undetected, only these two example modules are tested

**Comment by KaustubhPatange** [comment]
Hey, first of all, thanks for reporting.

 I just put a commit that fixes some of the memory leaks in the navigator library itself & also edited the samples. Let's talk about **navigation-sample**, found 2 leaks one from the library which is fixed other is related to how I wrote the sample so I changed the `SettingsFragment` in that sample which shows you how to correctly setup navigator in a fragment. This will change but for here is how.

Now about **multi-module-sample**, I wrote this sample based on an article I wrote [Scalable Navigation in Multi-Module projects](https://proandroiddev.com/scalable-navigation-in-multi-module-projects-c3c44dc1b913), basically, the fact is the sample here is a bit outdated so if you want to look a correct sample take a look at the sample mentioned in the library post. The reason it is outdated is that you should never keep a single instance of the fragment in your activity as that is a leak. In the current sample, I scope the `HomeFragment` to `HomeScope` which is an alias of `ActivityScope` i.e will be alive till the activity is alive no matter whether the fragment is added or removed from the container. This is a bad practice & should be avoided, you can find a correct implementation in the sample of the article I mentioned or take a look at one of my production apps [XClipper](https://github.com/KaustubhPatange/XClipper/tree/master/XClipper.Android) which is a multi-module app.

Now the reason why it crash is because I faced this challenge earlier when building the sample & couldn't get my mind wrapped around it. So basically, if you use `HomeFragment::class` in `navigateTo` you are creating a new `HomeFragment` which if you look deep in the sample in `HomeButtonClickedImpl` we are referencing it so at that point it creates a new `HomeFragment` which is not added in the container and hence the crash. 

All in all take a look at the sample I mentioned & you'll be good to go till I update the current sample :)

**Comment by xuexixuexijpg** [comment]
> 

ok i got it, thanks for the suggestion
